# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MGM5YjRlNTU4ZmYzMzVkMzljZjc3NDY2NjMzZjBiZWE0YmU4MTlmMjc2NTE3ZGZhMGNhYzkxYjQ3NGZiOWRlMGMzYTZlYTc4MGMxYjdkN2I5YTdmM2FkYTA3NzZhM2MzMjdhYWNhYzg4NGJkNTY4MTQzOWRiMjU0ZjkwN2NjYjQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
